### ISSUE TITLE
scale slider: should only render the new scaled display settings if mouse button has been released

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-a11y#34]
We are experiencing a bad usability regarding the scale slider, because whenever touching the slider and shifting it a little bit, all desktop elements resize immediately, also the slider itself. This make the slider not easily usable.

Alternative approach: slider can be moved, if slider has been released (or not been moved for 1s), the display scaling changes.

Additionally, we may want to think about an extra dialog popping up that asks if those settings are ok now, including a count down timer (15s) that will reset the previous settings unless the user confirms that the new settings are sane.

**Comment by tari01** [comment]
I haven't been too happy with the slider from the beginning, either. I also have an alternative to your alternative (been thinking about this for a while now): a button group similar to Caja's zoom that closes the menu immediately.
![Screenshot at 2024-07-08 14-35-32](https://github.com/AyatanaIndicators/ayatana-indicator-a11y/assets/9939853/5e92fd9a-3bfe-4481-8294-6cc78021efa6)
